### ISSUE TITLE
Incorrect behavior description for st.cache

### ISSUE THREAD

**Issue by AnOctopus** [streamlit/docs#100]
**Link to doc page in question (if any):** https://docs.streamlit.io/en/stable/api.html#streamlit.cache

**Name of the Streamlit feature whose docs need improvement:** cache

The docs for `allow_output_mutation` say:
```
Streamlit normally shows a warning when return values are not mutated, as that can have unintended consequences. This is done by hashing the return value internally.

If you know what you’re doing and would like to override this warning, set this to True.
```
However, based on the name, and behavior with the default value of False, it should say `Streamlit normally shows a warning when return values are mutated`, without the "not".

**Comment by snehankekre** [comment]
The "not" is no longer included in the docstring. A PR to remove "normally" is out here: https://github.com/streamlit/streamlit/pull/4095. Closing this issue for now.
