### ISSUE TITLE
3000 port is development port

### ISSUE THREAD

**Issue by kush99993s** [streamlit/docs#101]
**Link to doc page in question (if any):**
https://docs.streamlit.io/en/stable/streamlit_configuration.html

**Name of the Streamlit feature whose docs need improvement:**
Need to add a new line

**What you think the docs should say:**
Reserve port 3000 port in streamlit or reverse proxy. If you use it, it can do weird behavior 
Reserve port 3000 because it is used for the development

**Comment by sfc-gh-dmatthews** [comment]
This has been addressed in #962.
