### ISSUE TITLE
Docs show python version selector for Community Cloud that doesn't seem to exist

### ISSUE THREAD

**Issue by Asaurus1** [streamlit/docs#1012]
**Link to doc page in question (if any):**
https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app, specifically the Advanced Settings section.

**Name of the Streamlit feature whose docs need improvement:**
Community Cloud

**What you think the docs should say:**
Docs say that there should be a python version selector above the secret.toml text entry field: 
![image](https://docs.streamlit.io/images/streamlit-community-cloud/deploy-an-app-advanced.png)
But I am unable to find this field anywhere in App Settings for either of my Community Cloud apps: 
![image](https://github.com/streamlit/docs/assets/5677417/31a801cb-4829-44ee-9e86-9b0fcacdb36b)

**Comment by sfc-gh-dmatthews** [comment]
Hi @Asaurus1! 👋🏻 I just confirmed the dialog image is correct. What is shown on that page is how the dialog appears when deploying an app. It appears differently when [modifying an existing app](https://docs.streamlit.io/streamlit-community-cloud/manage-your-app/app-settings#update-your-secrets). You can't change the Python version of a deployed app; you have to delete and redeploy it currently.
