### ISSUE TITLE
Typo in example code

### ISSUE THREAD

**Issue by Ste1io** [streamlit/docs#1037]
This doesn't work due to `args` being a tuple:

https://github.com/streamlit/docs/blob/6641c367cc7f9e41f9639086045b120e5f5c2c16/content/develop/concepts/architecture/widget-behavior.md?plain=1#L171-L172

Should be `("my_key",)`.

**Comment by Asaurus1** [comment]
Yep this is a typo

**Comment by Ste1io** [comment]
I can open a PR with the fix.

**Comment by Ste1io** [comment]
On a somewhat different note, but regarding the same code block in terms of correctness and code clarity, wouldn't more appropriate names be `load_value` and `store_value`? This more accurately describes the transient operation being performed, which is more akin to loading and storing register values in assembly.

Notably, the term "get" in function names implies a return value, which is not the case here; it's simply loaded the permanent key's value into a transient key.

**Comment by sfc-gh-dmatthews** [comment]
@Ste1io, good comment. I'll add that to the commit.
