### ISSUE TITLE
Typo in Documentation: "tase" should be "taste"

### ISSUE THREAD

**Issue by bibekkd** [streamlit/docs#1041]
**Link to doc page in question (if any):**
https://docs.streamlit.io/get-started/fundamentals/additional-features

**Name of the Streamlit feature whose docs need improvement:**
In the fundamental section of the documentation, there are additional features discussed. However, in the first paragraph, a typo is present where the word "tase" appears instead of "taste." This error impacts the clarity and accuracy of the documentation, and it should be rectified to enhance user understanding.

**What you think the docs should say:**
The documentation should use the word 'taste' instead of 'tase' in the first paragraph of the fundamental section to accurately describe the concept being discussed.
![Screenshot 2024-04-21 025152](https://github.com/streamlit/docs/assets/135459655/3c8d5f68-d831-4c21-826b-9bdf5f5676e5)

**Comment by sfc-gh-dmatthews** [comment]
This has been corrected in #1043. Thanks!

**Comment by bibekkd** [comment]
my pleasure!
