### ISSUE TITLE
Search st.html goes to page not found

### ISSUE THREAD

**Issue by gabrieltempass** [streamlit/docs#1052]
### Summary

When searching for `st.html` and clicking on the result, it goes to **Page not found**, because the URL is wrong. The correct URL must have `.html` at the end.

### Steps to reproduce

1. Go to https://docs.streamlit.io
2. Click on the search bar
3. Type st.html
4. Select the first result

**Screen recording:**

![Kapture 2024-05-03 at 11 22 06](https://github.com/streamlit/docs/assets/41839984/6ca419f5-f6f2-4c36-9521-6095909ca73b)

**Expected behavior:**

Goes to: https://docs.streamlit.io/develop/api-reference/utilities/st.html

**Actual behavior:**

Goes to: https://docs.streamlit.io/develop/api-reference/utilities/st
(it's missing the .html at the end)

**Comment by sfc-gh-dmatthews** [comment]
Thanks for reporting! I think I have a fix for it that should get reviewed and published very soon.
