### ISSUE TITLE
Docs: Invalid link in Contributing Guide for Python unit tests

### ISSUE THREAD

**Issue by davidkrigbaum** [streamlit/docs#1191]
**Link to doc page in question (if any):** [https://github.com/streamlit/streamlit/wiki/Contributing#python-unit-tests](https://github.com/streamlit/streamlit/wiki/Contributing#python-unit-tests)

**Name of the Streamlit feature whose docs need improvement:**     Running tests: Python unit tests

**What you think the docs should say:**
The Contributing Guidelines specify in a fragment: 

> Some tests require you to [set up credentials](https://github.com/streamlit/streamlit/blob/main/.credentials/README.md) to connect to Snowflake and install [the snowflake-snowpark-python package](https://pypi.org/project/snowflake-snowpark-python/)

 But the link for 'set up credentials' leads to a '404 - page not found'.

The link should be updated to reflect current credentialing instructions or the wiki documentation should outline that information explicitly.

I found a potential link solution here: [https://docs.streamlit.io/develop/tutorials/databases/snowflake#add-connection-parameters-to-your-local-app-secrets](https://docs.streamlit.io/develop/tutorials/databases/snowflake#add-connection-parameters-to-your-local-app-secrets) but am unsure if this is what the dead link is supposed to reference. Please verify if this is the correct reference.

**Comment by davidkrigbaum** [comment]
I would like to volunteer to submit a PR to the wiki once the correct link is confirmed.

**Comment by sfc-gh-dmatthews** [comment]
Hi @davidkrigbaum! Thanks for reporting. I asked an engineer and they went ahead and corrected the section as some additional details changed as well.
