### ISSUE TITLE
Example code does not show the processed value stored in the session state

### ISSUE THREAD

**Issue by nshimbo** [streamlit/docs#1208]
### Summary
Document example code bug.
[Buttons to handle expensive or file-writing processes](https://docs.streamlit.io/develop/concepts/design/buttons#buttons-to-handle-expensive-or-file-writing-processes)
370 line in develop/concepts/app-design/button-behavior-and-examples.md

The current code only shows the raw value of add. To properly track and display how the "Add a number" option is being processed, we should modify the code to access the processed value from the session state instead.

Replace:
```
st.write(f'Option {option} processed with add {add}')
```
With:
```
st.write(f'Option {option} processed with add {st.session_state.processed[option][1]}')
```
This new code shows the processed value stored in the session state whenever the "Select a number" option changes.

**Comment by sfc-gh-dmatthews** [comment]
Thanks for raising the issue. To keep the code cleaner, I'll delete the second if block so the output from the widgets can be used to show what was just computed.
