### ISSUE TITLE
Need to upgrade Chroma version on community cloud.

### ISSUE THREAD

**Issue by yuvalsher** [streamlit/docs#1211]
### Summary

I have a python chatbot project that uses Chroma vector DB for RAG.
When deploying my app on community cloud I got this error:
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.
When I deploy on Render, it works fine.

### Steps to reproduce

Code snippet:

from langchain_chroma import Chroma

**Comment by sfc-gh-dmatthews** [comment]
Community Cloud uses Debian Linux. Currently, it's running on Debian 11 (bullseye), but Debian 12 (bookworm) should roll out soon along with support for Python 3.13.

Until bookworm is deployed, the latest version of sqlite3 is [3.34.1](https://packages.debian.org/bullseye/sqlite3). I've updated the limitations to clarify this.
