### ISSUE TITLE
We have found an issue with the sample code on the official website. The specific problem lies in "Example 4: Forms and callbacks" at “ https://docs.streamlit.io/develop/concepts/architecture/session-state ”.

### ISSUE THREAD

**Issue by ayiyi** [streamlit/docs#1212]
### Checklist

- [X] I have searched the [existing issues](https://github.com/streamlit/streamlit/issues) for similar issues.
- [X] I added a very descriptive title to this issue.
- [X] I have provided sufficient information below to help reproduce this issue.

### Summary

1. We have found an issue with the sample code on the official website. The specific problem lies in "Example 4: Forms and callbacks" at “ https://docs.streamlit.io/develop/concepts/architecture/session-state ”.
2. The below line should be added, otherwise the error message "AttributeError: stsession-state has no attribute" last_updated "will be reported.
`if 'last_updated' not in st.session_state: 
st.session_state.last_updated = datetime.time(0, 0)`
`

### Reproducible Code Example

```Python
import streamlit as st
import datetime

st.title('Counter Example')
if 'count' not in st.session_state:
    st.session_state.count = 0
    st.session_state.last_updated = datetime.time(0,0)

def update_counter():
    st.session_state.count += st.session_state.increment_value
    st.session_state.last_updated = st.session_state.update_time

with st.form(key='my_form'):
    st.time_input(label='Enter the time', value=datetime.datetime.now().time(), key='update_time')
    st.number_input('Enter a value', value=0, step=1, key='increment_value')
    submit = st.form_submit_button(label='Update', on_click=update_counter)

st.write('Current Count = ', st.session_state.count)
st.write('Last Updated = ', st.session_state.last_updated)
```

### Steps To Reproduce

1. run the code.
2. then you will see the AttributeError

### Expected Behavior

Update sample code:
`if 'last_updated' not in st.session_state: 
st.session_state.last_updated = datetime.time(0, 0)`
`

### Current Behavior

AttributeError: st.session_state has no attribute "last_updated". 

### Is this a regression?

- [ ] Yes, this used to work in a previous version.

### Debug info

- Streamlit version:1.30.0
- Python version:3.11.5
- Operating System:win11
- Browser:edge

### Additional Information

![image](https://github.com/user-attachments/assets/7a4888a5-bef3-4009-93af-1e46d21d7078)

**Comment by sfc-gh-dmatthews** [comment]
I do not get an AttributeError when running this code. In order to trigger the error, you'd need to initialize "count" in Session State with some other code, then paste this code into an already running Streamlit server. Modifying code while running a Streamlit app can certainly have unintended consequences, but this works as-is if run cleanly. 😄
