### ISSUE TITLE
Doc pages never finish loading and Ask AI not working

### ISSUE THREAD

**Issue by nick-youngblut** [streamlit/docs#1216]
### Summary

None of the doc pages finish loading, and the `Ask AI` button is unresponsive. 

If I switch to Safari, there are no issues: pages fully load and the `Ask AI` button functions correctly.

### Steps to reproduce

* Chrome: 131.0.6778.205 (Official Build) (arm64)
* MacOS: 15.2 (24C101)

Screenshot(s):

<img width="842" alt="Screenshot 2024-12-30 at 12 14 12 PM" src="https://github.com/user-attachments/assets/205e7193-dd0b-45d1-8989-7f799d9d3e15" />

**Expected behavior:**

See above

**Actual behavior:**

See above

### Debug info

See above

**Comment by sfc-gh-dmatthews** [comment]
Thanks for reporting. I tried the same version of Chrome and Mac and can't reproduce the issue. Can you clear your cache and try loading the page again?

**Comment by nick-youngblut** [comment]
Yeah, clearing the cache fixed the issue. Sorry to waste your time.
