### ISSUE TITLE
Secrets screenshot is outdated

### ISSUE THREAD

**Issue by arnaudmiribel** [streamlit/docs#132]
This image [public/images/databases/edit-secrets.png](https://github.com/streamlit/docs/blob/main/public/images/databases/edit-secrets.png) is outdated:

<img src="https://user-images.githubusercontent.com/7164864/138300157-f619a51c-4d7f-432c-bab3-f9f1ca7ca158.png" width=200></img>

Also [this page has outdated screenshots](https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management)

This now looks different. And might also change soon (`Environment` in favor of  `Secrets`), so need to keep that in mind.**

<img src="https://user-images.githubusercontent.com/7164864/138300366-f1d9f96c-45a4-41c5-8229-96f48399a1ad.png" width=300></img>

**Comment by randyzwitch** [comment]
Closed by #176
