### ISSUE TITLE
"App model" fragment in the "Main concepts" docs page seems broken

### ISSUE THREAD

**Issue by vdonato** [streamlit/docs#159]
Navigating to https://docs.streamlit.io/library/get-started/main-concepts#app-model does not scroll the page down to the corresponding section. I tried navigating to a few other parts of the page via fragment, and they don't seem to be running into the same issue.

What seems to be a related bug is present when clicking on the page navigation links on the right hand side of the page -- clicking on the "App model" link brings you to the caching header.

**Comment by snehankekre** [comment]
Thanks for filing this bug report @vdonato! We're working on a fix.
