### ISSUE TITLE
Docs UI glitch between 1025px and 1249px screen width

### ISSUE THREAD

**Issue by StefanBrand** [streamlit/docs#175]
## Problem

Between 1025px and 1249px screen width, the side bar overlays docs content, even if collapsed. Tested in Firefox 94.0 on my 1280x1024px screen (due to Ubuntu dash bar, actual browser window width is 1204px).

The screenshot demonstrates the behaviour. It is not possible to click links under the red area.
![image](https://user-images.githubusercontent.com/8948865/142172251-5e88edc2-37d9-4b0a-b17d-07c739138770.png)

## Solution
Fix media queries

## Workaround

Zoom out or make window width smaller than 1025px.

**Comment by StefanBrand** [comment]
This still happens to me on https://docs.streamlit.io/library/changelog

**Comment by snehankekre** [comment]
Thanks for reporting this @StefanBrand. Reopening this issue and looping in @imjuangarcia to take a look.
