### ISSUE TITLE
Help Need: pip version issue

### ISSUE THREAD

**Issue by andywrq** [streamlit/docs#314]
You are using pip version 21.1.1; however, version 22.0.3 is available.

You should consider upgrading via the '/home/appuser/venv/bin/python -m pip install --upgrade pip' command.

**Comment by randyzwitch** [comment]
Hi @andywrq - 

This is an issue with pip, not Streamlit. Do you have a question about this, or are you suggesting we add something to our  documentation?

Best,
Randy
