### ISSUE TITLE
Supabase as a Data Source for Streamlit

### ISSUE THREAD

**Issue by J0** [streamlit/docs#325]
Hey Streamlit,

I am one of the maintainers of the [python client libraries](https://github.com/supabase-community/supabase-py) for [Supabase](https://github.com/supabase/supabase) . Supabase is, loosely speaking, an open source firebase. Streamlit is a great product and I was hoping that we could file a PR with a guide on how to use Supabase as a data source for Streamlit. 

Wanted to seek your approval before doing this though.

Let us know!
Joel

**Comment by randyzwitch** [comment]
Hi @J0 - 

Supabase looks like a great project, please go ahead and make a tutorial in a similar style to the ones that already exist!

Best,
Randy

**Comment by nadirkartal** [comment]
Thank you for your help

**Comment by J0** [comment]
@randyzwitch have opened a PR, looking forward to your review whenever ready
