### ISSUE TITLE
Documentation text color issue

### ISSUE THREAD

**Issue by osbm** [streamlit/docs#363]
Here is the [link](https://docs.streamlit.io/library/api-reference/layout/st.columns)

This bit in the documentation when using the black theme is not readable.

![image](https://user-images.githubusercontent.com/74963545/161400282-59fb0028-40ce-48e7-b09c-ad837c64f92d.png)

**Comment by snehankekre** [comment]
Thank you for reporting this bug, @osbm! We'll work on a fix shortly.
