### ISSUE TITLE
Confusion about python package management in "get started" docs

### ISSUE THREAD

**Issue by Franky1** [streamlit/docs#366]
Mixing and mentioning different python packet managers is maybe confusing for beginners, especially if they move on from local development to streamlit cloud.

This is related to this forum thread:

<https://discuss.streamlit.io/t/modulenotfounderror-despite-simple-requirements-txt-present/23795/10>

> [The documentation](https://docs.streamlit.io/library/get-started/installation) first recommends to use pipenv and Pipfile for dependencies
But [the next page](https://docs.streamlit.io/library/get-started/create-an-app) says: “1. Put your app in a public GitHub repo (and make sure it has a requirements.txt!)”

> Thanks but for a normal user who reads the documentation in order the first page is “[Installation](https://docs.streamlit.io/library/get-started/installation)” where you’re told to use Pipfile and the next page is “[Create an app](https://docs.streamlit.io/library/get-started/create-an-app)” where you’re told to “make sure it has a requirements.txt!”.
It would be great to add a link to that page (“App dependencies”) in the “Installation” page of the documentation. And to mention clearly there that “You should only use one requirements file for your app. If you include more than one (e.g. requirements.txt and Pipfile). Streamlit will first look in the directory of your Streamlit app; however, if no requirements file is found, Streamlit will then look at the root of the repo.”

**Comment by snehankekre** [comment]
Thanks for reporting this issue @Franky1. We'll  work on a fix this week.

**Comment by Franky1** [comment]
I would probably stick to `pip` and `requirements.txt` because IMHO this is the easiest and most common python packet manager? I know there are newer package managers that may be a bit more modern.

**Comment by a455bcd9** [comment]
Whatever the solution adopted, I think a link to [App dependencies](https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/app-dependencies) should be added every single time `requirements.txt` is mentioned. For instance: https://docs.streamlit.io/knowledge-base/tutorials/databases/private-gsheet

If `Pipfile` stays as the recommended requirements file format then it would be good to provide an example of a typical `Pipfile` and how it's formatted. Otherwise, I assume many users will first (as I did...) copy-paste the content from their `requirements.txt` (which doesn't work, obviously haha).

**Comment by MathCatsAnd** [comment]
I was going to publish a PR to fix some broken links in Getting Started and would be happy to review for package management consistency at the same time. Just posting for coordination/communication. :)

**Comment by MathCatsAnd** [comment]
I have some other thoughts, but first, related to a PR going through right now:
https://github.com/streamlit/docs/pull/620 re: [Installation page](https://docs.streamlit.io/library/get-started/installation)

I was thinking of removing Python and pip as "prerequisites" so as not to give new users the idea to try and sort that out for themselves first. For Windows, I usually advise people to just go straight to Anaconda if they are starting fresh; I find there is less confusion if you can save new users from having multiple installations of Python.

If just having them have their IDE ready is the only "prerequisite" then:

1. Windows is just install Anaconda, create the environment, and `pip install streamlit`. (Python and PIP installations are handled by Anaconda, no muss, no fuss.)
2. Linux and Mac would then direct users to install Python first (if not already installed, maybe a one liner to check?) then pick up at installing pip as it is now.

Side note: I've installed Miniconda on Linux before and pip installed streamlit just fine. And Anaconda Navigator has installations for Mac and Linux, too. Are there issues with using conda for Mac and Linux? The logical flow of the Windows instructions is (Python)->Environment Management->Package Management->Installation. Mac and Linux goes Python->Package Management->Environment Management->Installation. I like the logical flow on the Windows side much better myself as it feels more natural, conceptually for new users. (We create environments and then manage packages within them, not the other way around exactly.)

**Comment by sfc-gh-dmatthews** [comment]
There is an MVP improvement to the installation docs pending in #871. As part of a larger review of the site's information architecture, we're planning to move the Get started section up to its own top-level category and introduce more of the options for where and how you can code with Streamlit. We will follow up to explain additional options in the installation section as well as revamp the initial explanation of concepts and tutorials.

An earlier PR (#766) reworked some of the content within the Community Cloud section regarding requirements.txt and we're using `requirements.txt` as the default in our tutorials.

I plan to close this with #871.
