### ISSUE TITLE
An example in st.dataframe docs is missing

### ISSUE THREAD

**Issue by WestedCrean** [streamlit/docs#373]
**Link to doc page in question (if any):**

https://docs.streamlit.io/library/api-reference/data/st.dataframe#stdataframe

**Name of the Streamlit feature whose docs need improvement:**

Code output/result

**What you think the docs should say:**

There are 3 code cells but only 2 outputs. The middle one, `st.dataframe(df, 200, 100)` has no output for example of streamlit dataframe component resized.

![obraz](https://user-images.githubusercontent.com/11256405/163583498-5ef77229-934e-4499-b646-db6b6eb4c3f0.png)

**Comment by MathCatsAnd** [comment]
I think this line can just be removed:

https://github.com/streamlit/streamlit/blob/3f6e47e7aa53c1419ec8d432671d86c205da48e9/lib/streamlit/elements/dataframe_selector.py#L95

**Comment by MathCatsAnd** [comment]
@snehankekre I don't have permission to officially set you as reviewer on pull requests, so here's a ping since you aren't listed on this issue yet and the PR is on the main library. :)

**Comment by MathCatsAnd** [comment]
@snehankekre or @WestedCrean I think this issue can be closed now; it looks like it didn't auto-close with the merge. :)
