### ISSUE TITLE
DuplicateWidgetID when running code in "Authentication without SSO" 

### ISSUE THREAD

**Issue by dehiker** [streamlit/docs#415]
### Summary
When running code demo in [Step 3: Ask for username & password in your Streamlit app](https://github.com/streamlit/docs/blob/main/content/kb/deployments/authentication-without-sso.md#step-3-ask-for-username--password-in-your-streamlit-app), got error:
`streamlit.errors.DuplicateWidgetID: There are multiple identical `st.text_input` widgets with `key='username'`.`

### Steps to reproduce

Code snippet:
See summary.

Screenshot(s):
NA

**Expected behavior:**
No errors in terminal

**Actual behavior:**
See summary.

**Comment by snehankekre** [comment]
Hi @dehiker 👋 thanks for reporting this issue. Are you sure you haven't modified the code such that both `st.text_input` widgets are within the same `if` block?

Unfortunately, I'm unable to reproduce the error locally and on Streamlit Cloud. I deployed an [app](https://share.streamlit.io/snehankekre/auth-without-sso/main) with the identical code. The correct password is `test`. Note that no error is thrown if you enter the right or incorrect password.

To double-check, run the following and check if you observe any errors:

```shell
$ git clone https://github.com/snehankekre/auth-without-sso.git
$ cd auth-without-sso/
$ pip install -r requirements.txt
$ streamlit run streamlit_app.py
```

If running the above doesn't lead to errors, it is very likely you have inadvertently modified the code from the docs.

**Comment by snehankekre** [comment]
You're seeing an error by deploying this app (https://github.com/dehiker/streamlit-example/blob/6756396f8e42396c07496f0e8ec2b1256766cd78/st_utils.py#L23-L24) because there are two text input widgets with the same key in one if block. i.e. the code is not identical to that in the docs.
