### ISSUE TITLE
plot,ly example keeps failing

### ISSUE THREAD

**Issue by itsclint** [streamlit/docs#426]

**Comment by snehankekre** [comment]
Hi @itsclint, thanks for reaching out. Could you please provide more information about the issue? What example keeps failing? It would help if you also provide a reproducible code example, as well as info about your OS, and the versions of Streamlit and Plotly Python you have installed. 🙂 

The example on the [st.plotly_chart](https://docs.streamlit.io/library/api-reference/charts/st.plotly_chart) docs page works without issues locally and on Streamlit Cloud: https://share.streamlit.io/streamlit/docs/main/python/api-examples-source/charts.plotly_chart.py

**Comment by snehankekre** [comment]
Feel free to reopen this issue or create a new one if you're able to go into more detail, as requested [above](https://github.com/streamlit/docs/issues/426#issuecomment-1168290189).
