### ISSUE TITLE
Style to hide Index of st.table() fails when --global.dataFrameSerialization="legacy"

### ISSUE THREAD

**Issue by naokimaejima** [streamlit/docs#439]
**Link to doc page in question (if any):**
https://docs.streamlit.io/knowledge-base/using-streamlit/hide-row-indices-displaying-dataframe

**Name of the Streamlit feature whose docs need improvement:**
`st.table()` (in the knowledge base)

**What you think the docs should say:**
The knowledge base above offers a stylesheet to hide Index in `st.table()`
But it fails when `--global.dataFrameSerialization="legacy"`. 
Here’s an example. I use streamlit v1.11.0.

[app.py]
```python
import pandas as pd
import streamlit as st

hide_table_row_index = """
            <style>
            tbody th {display:none}
            .blank {display:none}
            </style>
            """

st.markdown(hide_table_row_index, unsafe_allow_html=True)
df = pd.DataFrame({"col1":[1,2,3],"col2":[1,2,3]})
st.table(df)
"""

st.markdown(hide_table_row_index, unsafe_allow_html=True)
df = pd.DataFrame({"col1":[1,2,3],"col2":[1,2,3]})
st.table(df)
```

- `streamlit run app.py ` 

![image](https://user-images.githubusercontent.com/36030348/180410658-c94fe7e0-dafa-4e5d-af39-97c080fb0668.png)

- `streamlit run app.py --global.dataFrameSerialization="legacy"` 

![image](https://user-images.githubusercontent.com/36030348/180410567-c991550f-6489-4201-b13c-1949b7959c6c.png)

I think the style as below is a better way to robustly hide the Index, without depending on the method of selization of the dataframe.
This works even if `--global.dataFrameSerialization="legacy"`.

```html
<style>
thead tr th:first-child {display:none}
tbody th {display:none}
</style>
```

**Comment by snehankekre** [comment]
Hi @naokimaejima 👋 thank you for reporting the issue and contributing with a solution! A fix is on its way.
