### ISSUE TITLE
Suggest for the st.empty documentation 

### ISSUE THREAD

**Issue by lde2015** [streamlit/docs#458]
**Link to doc page in question (if any):**
https://docs.streamlit.io/library/api-reference/layout/st.empty

**Name of the Streamlit feature whose docs need improvement:**

**What you think the docs should say:**
        >>>
        >>> # Replace the placeholder with some text:
        >>> placeholder.text("Hello")
        **>>> time.sleep(5)**
        >>>
        >>> # Replace the text with a chart:
        >>> placeholder.line_chart({"data": [1, 5, 2, 6]})
        **>>> time.sleep(5)**
        >>>
        >>> # Replace the chart with several elements:
        >>> with placeholder.container():
        ...     st.write("This is one element")
        ...     st.write("This is another")
        ...
        **>>> time.sleep(5)**
        >>>
        >>> # Clear all those elements:
        >>> placeholder.empty()
        **>>> time.sleep(0.01)**
        >>>  
        **>>> # Replace the chart again:**
        **>>> with placeholder.container():**
        **>>>      st.write("===> This is another one !!!")**

**Comment by sfc-gh-dmatthews** [comment]
Closing this issue since the `st.empty` example was updated in Version 1.39.0. 😄
