### ISSUE TITLE
navigation between pages - unclear

### ISSUE THREAD

**Issue by keiranmraine** [streamlit/docs#462]
**Link to doc page in question (if any):**
https://docs.streamlit.io/library/get-started/multipage-apps#navigating-between-pages

**Name of the Streamlit feature whose docs need improvement:**
How to create a link that doesn't result in a new tab/window when navigating between pages in the streamlit app.

**What you think the docs should say:**
Not sure, there are many unanswered questions on this in the forum.  I want to go from the "main" page to a side-bar page (optionally with anchor).  Both using `st.write()` and `st.markdown()` result in a new window/tab and full reload of the site.

Sidebar page `pages/Definitions.py`

Link code possibilities both appear to function the same way, find the page, but start a new window:
```py
st.write('find docs [here](./Definitions)')
# or
st.markdown('find docs [here](./Definitions)')
```

**Comment by MathCatsAnd** [comment]
I linked an issue about about adding programmatic options for changes pages if that happens to interest you. There are definitely limitations in navigating between pages outside of the default sidebar menu so it would certainly make sense to clarify those limitations explicitly. I'm not sure if I've ever seen it worked out in simple terms for markdown. To switch pages, you have to communicate to the Python backend to facilitate that change if you don't want to start a new session and that requires a custom component.

**Comment by janaka** [comment]
Doc improvement in PR #728 is also related to this.
