### ISSUE TITLE
AWS S3 connection example breaks without AWS_DEFAULT_REGION

### ISSUE THREAD

**Issue by JoshuaC215** [streamlit/docs#473]
**Link to doc page in question (if any):** https://docs.streamlit.io/knowledge-base/tutorials/databases/aws-s3

**Name of the Streamlit feature whose docs need improvement:** AWS S3 connection (as documented in the provided example)

**What you think the docs should say:**

Configuring an AWS client with environment variables requires `AWS_DEFAULT_REGION` to be included or most clients will not fully recognize the creds (regardless of whether it's actually used). As written [here](https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html) and in most other AWS docs on the subject.

This is not obvious, nor is it included in the current documentation for pulling data from an S3 bucket in Streamlit. Currently, using the example config verbatim causes the user to get a fairly opaque 403 for pulling data from a non-public bucket.

Suggested fix would be to just include this in the example. I am submitting a PR with this change. I considered whether or not to explicitly call this requirement out in the doc - didn't include that in my PR but maybe worth consideration.

**Comment by snehankekre** [comment]
Thanks so much for creating this issue and submitting a PR! I've made some minor additions and have [approved](https://github.com/streamlit/docs/pull/474#pullrequestreview-1098670277) your changes. LMK what you think of the changes and if there's anything else we should call out in the PR.
