### ISSUE TITLE
TiDB as a data source for streamlit

### ISSUE THREAD

**Issue by zhangyangyu** [streamlit/docs#507]
Hi streamlit folks,

I am from TiDB community. [TiDB](https://github.com/pingcap/tidb) is an open source distributed HTAP NewSQL database and fit for real-time analytics. There is also a [TiDB Cloud](https://www.pingcap.com/tidb-cloud/). Streamlit is wonderful especially I am also a Python developer. :-) I wonder if I could submit a PR to add TiDB to [the data source list](https://docs.streamlit.io/knowledge-base/tutorials/databases). How do you think?

Thanks!

**Comment by snehankekre** [comment]
Hi @zhangyangyu 👋 

TiDB looks like a great project, please go ahead and make a tutorial in a similar style to the ones that already exist!

Best,
Snehan 🎈
