### ISSUE TITLE
Streamlit compatibility for python 3.11

### ISSUE THREAD

**Issue by dove88** [streamlit/docs#511]
I like to work with python 3.11 and streamlit, as i was trying to install streamlit, dependent library pyarrow was not installing due to compatibility issue with python version.

Kindly advise.

**Comment by snehankekre** [comment]
Hi @dove88 👋 

Streamlit will maintain backwards-compatibility with earlier Python versions as practical, guaranteeing compatibility with at least the last three minor versions of Python 3.

As new versions of Python are released, we will try to be compatible with the new version as soon as possible, though frequently we are at the mercy of other Python packages to support these new versions as well.

Streamlit currently supports versions 3.7, 3.8, 3.9, and 3.10 of Python. Unfortunately, Python 3.11 is not a Streamlit-supported version of Python 😞 

Source: https://docs.streamlit.io/knowledge-base/using-streamlit/sanity-checks

**Comment by dove88** [comment]
Thank you
