### ISSUE TITLE
Error running app. If this keeps happening, please contact support.

### ISSUE THREAD

**Issue by VictorWCS2022** [streamlit/docs#534]
I can not see the vizualisations

**Comment by snehankekre** [comment]
Hi, thank you for reporting the issue.

> I can not see the vizualisations

You probably meant a few embedded apps in the documentation were down. The issue has been fixed and all embedded apps are back online. 🎈

The next time, please include more information in your issue, including what visualisations you were unable to see and on what pages. 

Happy Streamlit-ing!
