### ISSUE TITLE
Explicity mentioning that (local?) configuration changes requires a restart of server

### ISSUE THREAD

**Issue by achieveordie** [streamlit/docs#535]
Hey,
I'm a new user and while going through the docs and trying things, I found that there is possibly some scope for improvement in the documentation. I'm not sure if this also applies to global configurations but it certainly is valid for local configurations.

This is useful for the typical case where users are setting up their own `.streamlit/config.toml` for their project while the app is already running.

**Link to doc page in question (if any):**
Either of [Configuration](https://docs.streamlit.io/library/advanced-features/configuration) or [Theming](https://docs.streamlit.io/library/advanced-features/theming)

**Name of the Streamlit feature whose docs need improvement:**
This can possibly be added in the later part of the introduction of either section.

**What you think the docs should say:**
- If changes are made in `Configuration`:  This list is in reverse order of precedence, i.e. command line flags take precedence over environment variables when the same configuration option is provided multiple times. **Please note that the server needs to be restarted for changes in local configuration (like per-project config) file to be reflected in the app.**
- If changes are made in `Theming`: 
The following config options show the default Streamlit Light theme recreated in the `[theme]` section of a `.streamlit/config.toml` file.

``` toml
[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
```
**The server needs to be restarted after changing the values for it to be reflected in the app.**

I can make a PR fixing this if my EP is accepted.
Thanks.

**Comment by snehankekre** [comment]
Hi @achieveordie 👋 

Thank you for first submitting an issue and for your patience! 

Really good points: command line flags take precedence; if changes to `.streamlit/config.toml` are made _while_ the app is running, the server needs to be restarted for the config options to be reflected in the app.

Your proposal looks good to me. Feel free to create a PR and I'll review+merge it. 😃
