### ISSUE TITLE
label text is not shown if it contains unsupported Markdown in 1.15.0

### ISSUE THREAD

**Issue by Bomme** [streamlit/docs#557]
### Checklist

- [X] I have searched the [existing issues](https://github.com/streamlit/streamlit/issues) for similar issues.
- [X] I added a very descriptive title to this issue.
- [X] I have provided sufficient information below to help reproduce this issue.

### Summary

After upgrading to 1.15.0 the text labels for a few widgets disappeared in our app.
After some investigation, I found that it happens if the text contains (unintended) markdown syntax.

I was surprised that the label text is not shown at all in that case.

### Reproducible Code Example

```Python
import streamlit as st

st.button(" 1. choice (not shown)", key="one")
st.button(" 2\. choice (escaping as a work around)", key="two")
```

### Expected Behavior

I expect the label to be shown as it was before. (No markdown rendering)

### Current Behavior

<img width="314" alt="Bildschirmfoto 2022-11-22 um 21 34 12" src="https://user-images.githubusercontent.com/13520622/203415719-6a0d0d08-4763-42d6-aec4-9b7177802ccf.png">

### Is this a regression?

- [X] Yes, this used to work in a previous version.

### Debug info

- Streamlit version: 1.15.0
- Python version: Python 3.10.8
- Operating System: macos 12.6.1 
- Browser: tested on Chrome and Firefox
- Virtual environment: venv

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

**Comment by snehankekre** [comment]
Closing as this was fixed last month by: https://github.com/streamlit/streamlit/pull/5978
