### ISSUE TITLE
Improve your website with documentaion, please!

### ISSUE THREAD

**Issue by Arseni1919** [streamlit/docs#561]
### Checklist

- [X] I have searched the [existing issues](https://github.com/streamlit/streamlit/issues) for similar issues.
- [X] I added a very descriptive title to this issue.
- [X] I have provided sufficient information below to help reproduce this issue.

### Summary

If I enter any documentation page in your website - https://docs.streamlit.io/library/api-reference - something strange is happenning - the page reloads itself several times, and it is very hard to go back therefore. The website also crashes because of this. I attached video that shoows the issue. Please, fix!

One minor thing: The "Contact Us" link in the footer of the website also does not help. It brings me directly to my Mail app on my Mac which I didn't configured (and don't want to). Just show your email explicitly on the website - and it will be perfect.
Thank you!

### Is this a regression?

- [ ] Yes, this used to work in a previous version.

### Debug info

- Streamlit version:
- Python version:
- Operating System:
- Browser:
- Virtual environment:

### Additional Information

https://user-images.githubusercontent.com/55444116/211796207-b9063ea5-7ca5-4430-949b-3072359ee99b.mov

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

**Comment by snehankekre** [comment]
Thank you for reporting this issue @Arseni1919! We're aware that the site or your browser tab become unresponsive when specifically when viewing multiple API reference pages in succession. We're investing the issue and will let you know once it's fixed.

**Comment by Arseni1919** [comment]
One minor thing: The "Contact Us" link in the footer of the website also does not help. It brings me directly to my Mail app on my Mac which I didn't configured (and don't want to). Just show your email explicitly on the website - and it will be perfect.
Thank you!
