### ISSUE TITLE
Snowflake connection page could be revamped

### ISSUE THREAD

**Issue by tylerjrichards** [streamlit/docs#581]
**Link to doc page in question (if any):** https://docs.streamlit.io/knowledge-base/tutorials/databases/snowflake

The snowflake connection docs leave a lot to be desired! 

1. we should use the new snowflake UI as a default
2. we should tell people about the external browser connection options for snowflake
3. it takes like 10 pages to get to the point, there should be a TLDR at the top with best practices that is viewable on a single page
4. we should tell people to run select current_account() to get the account identifier

if I have time i'll fix this but I noticed the quality was much lower than our other docs

**Comment by sfc-gh-jcarroll** [comment]
I did some improvements on it with the st.connection re-write, but noticed some similar things and got similar feedback from a couple sales engineers.

Should definitely see if we can improve it further soon - this one gets a lot of traffic, it should be high quality!

**Comment by sfc-gh-dmatthews** [comment]
@tylerjrichards I have a first-draft rewrite of the tutotialin the linked PR above. It also shows edits to the docstrings that should go into 1.40.0. Let me know what you think!
