### ISSUE TITLE
None of the embedded docs.streamlit.io apps load properly on Safari

### ISSUE THREAD

**Issue by cwhatley** [streamlit/docs#585]
### Summary

The embedded apps on the doc site don't work on Mac or iPhone Safari (and haven't ever worked for me in the last year). Even if I pop out to view them standalone, they fail to load. Chrome seems OK.

E.g., https://docs.streamlit.io/library/api-reference/charts/st.area_chart

See a lot of console errors on the doc page:

![image](https://user-images.githubusercontent.com/573757/216145527-729f079c-c5ee-4759-9d39-36125787d615.png)

When I open the doc app standalone:

![image](https://user-images.githubusercontent.com/573757/216146916-7228e833-e959-485c-96c0-14342e116be2.png)

For mac I'm on Ventura with Safari Version 16.3 (18614.4.6.1.5), but as I said, I've seen the same thing going back at least a year.

**Comment by snehankekre** [comment]
Thank you for reporting this serious issue, @cwhatley! Our Community Cloud team is taking a look. I'll update this thread once we've made progress and/or have a resolution. Give us another week.

**Comment by snehankekre** [comment]
I believe the Community Cloud team fixed this issue in April, so I'm marking this as resolved. Please let us know if you're still facing issues with embedded docs apps and we'll reopen the issue.
