### ISSUE TITLE
No such file or directory: 'model.pkl

### ISSUE THREAD

**Issue by mariammagd** [streamlit/docs#587]
_(Note, you don't have to fill out every section here. They're just here for guidance. That said, nicely detailed feature requests are more likely to get eng attention sooner)_

### Problem

Is your feature request related to a problem? Please describe the problem here. Ex. I'm always frustrated when [...]

### Solution

**MVP:** What's the smallest possible solution that would get 80% of the problem out of the way?

**Possible additions:** What are other things that could be added to the MVP over time to make it better?

**Preferred solution:** If you don't like the MVP above, tell us why, and what you'd like done instead.

### Additional context

Add any other context or screenshots about the feature request here. For example, did this FR come from <https://discuss.streamlit.io> or another site? Link the original source here!

**Comment by snehankekre** [comment]
If you're having trouble loading machine learning models, please ask a question in our [discussion forum](https://discuss.streamlit.io/) instead, adhering to our posting [guidelines](https://discuss.streamlit.io/t/using-streamlit-how-to-post-a-question-in-the-streamlit-forum/30960).
