### ISSUE TITLE
st.experimental_data_editor vs st.data_editor

### ISSUE THREAD

**Issue by asehmi** [streamlit/docs#599]
**Link to doc page in question (if any):**
https://github.com/streamlit/docs/blob/main/content/library/advanced-features/dataframes.md

**Name of the Streamlit feature whose docs need improvement:**
st.experimental_data_editor

**What you think the docs should say:**
There are references in the sample code blocks and text to `st.data_editor` where they probably should be `st.experimental_data_editor`.

**Comment by snehankekre** [comment]
Thank you for reporting this issue, @asehmi! 🔍
