### ISSUE TITLE
Update TiDB tutorial to use st.experimental_connection

### ISSUE THREAD

**Issue by sfc-gh-jcarroll** [streamlit/docs#633]
### Problem

We recently launched [st.experimental_connection](https://blog.streamlit.io/introducing-st-experimental_connection/) and support for community connections.

Given that we had past interest in connecting Streamlit to TiDB, it might be useful to update the [current tutorial](https://docs.streamlit.io/knowledge-base/tutorials/databases/tidb) to use this approach.

Per discussion in https://github.com/pingcap/docs/issues/13396 the recommended approach is to use the built in SQLConnection with the [TiDB SQLAlchemy driver](https://github.com/pingcap/sqlalchemy-tidb) assuming we verify it works easily enough.

### Additional context (if relevant)

Connections can be built by extending [ExperimentalBaseConnection](https://docs.streamlit.io/library/api-reference/connections/st.connections.experimentalbaseconnection). We've built a few examples:

- https://github.com/streamlit/files-connection
- https://github.com/streamlit/gsheets-connection
- https://github.com/streamlit/release-demos/blob/master/1.22/st-experimental-connection/duckdb_connection/connection.py

If someone is interested in taking this on and setting up the repo, would be happy to discuss, do code review, or set up a quick call to discuss.

(Same goes for other relevant data stores / data sources!)

**Comment by sfc-gh-jcarroll** [comment]
Hi @zhangyangyu I saw you originally wrote the TiDB tutorial for Streamlit - wondered if you had any interest in this or knew anyone else who might? Thanks!

**Comment by zhangyangyu** [comment]
@sfc-gh-jcarroll I'll take a look later.

**Comment by sfc-gh-jcarroll** [comment]
Thank you!! If you have any feedback on using st.experimental_connection let us know 😄
