### ISSUE TITLE
Social Media Link Update

### ISSUE THREAD

**Issue by MathCatsAnd** [streamlit/docs#653]
The social media links on the documentation site are missing some of the ones listed on the community section of streamlit.io.

Need to add Medium, LinkedIn, and Newsletter to match the main site. (Additionally, Reddit is missing, but that is also missing from the main site.)

I will submit a PR.

**Comment by MathCatsAnd** [comment]
I saw Reddit was added to the top navigation on discuss.streamlit.io, so I took a stab at adding it to the docs sight accordingly. There wasn't an icon to copy, so I grabbed it from Reddit's branding documentation and attempted to comply with the branding requirements.

**Comment by snehankekre** [comment]
Can't thank you enough for taking this on! Totally forgot to add our new Reddit channel to the footer. @carolinedlu's going to love this!

**Comment by snehankekre** [comment]
Good call. cc @carolinedlu ^^
