### ISSUE TITLE
`st.image` introductory example should not import PIL

### ISSUE THREAD

**Issue by edsaac** [streamlit/docs#681]
**Link to doc page in question (if any):**
https://docs.streamlit.io/library/api-reference/media/st.image

**Name of the Streamlit feature whose docs need improvement:**
st.image

**What you think the docs should say:**
The current example points users to import `PIL.Image` and use the `Image.open`  method to open an image file from a relative path. 

_Current example:_
``` python
import streamlit as st
from PIL import Image

image = Image.open('sunrise.jpg')
st.image(image, caption='Sunrise by the mountains')
```

Most users just have a relative path or an url to an image. Those can be passed directly to `st.image` without the need of the user importing the PIL module.

_Proposed example:_
```python
import streamlit as st

path_to_image = "sunrise.jpg"
st.image(path_to_image, caption="Sunrise by the mountains")

url_to_image = "https://placekitten.com/500/500"
st.image(url_to_image, caption="Cat!")
```

*****

In addition, the proper way to handle files with PIL is with a context manager (see [*File handling in pillow*](https://pillow.readthedocs.io/en/stable/reference/open_files.html#file-handling-in-pillow) for details). In short, the current example in the documentation does not take care of closing the image file, which is fine to a certain extent in a normal python script, but this can lead to funky behavior when many users run the app. See this issue for example [on discuss](https://discuss.streamlit.io/t/image-partially-displayed-as-black-box-in-streamlit-app-after-deployment/42283). 

__Proposed example with context manager:__
```python
import streamlit as st
from PIL import Image

with Image.open('sunrise.jpg') as image:
    st.image(image, caption='Sunrise by the mountains')
```

**Comment by sfc-gh-dmatthews** [comment]
PIL was removed from the example with streamlit/streamlit#7728. Closing. 😄
