### ISSUE TITLE
Best practises deployment scalable ML model

### ISSUE THREAD

**Issue by bertChristiaens1** [streamlit/docs#712]
Dear streamlit, I love using your framework for ML applications, eg on Huggingface spaces. I was wondering what is considered the best way to handle multiple users accessing the same ML models at the same time. In HF spaces, I can’t deploy the models on an external API, so it has to be loaded into memory, which can ‘explore’ when inference happens for multiple users at the same time.

Im using the model as a shared resource, is there a good way to make a Queue / distribute the inference calls accross sessions?

**Comment by sfc-gh-dmatthews** [comment]
👋🏻 Hi! I'll refer this question to our [forums](https://discuss.streamlit.io/) and close this issue since we track changes to the documentation here. 😄
