### ISSUE TITLE
Published component is not visible in Streamlit component gallery

### ISSUE THREAD

**Issue by Vishnu-Moorthi** [streamlit/docs#746]
## Issue

We have published the component on July 07, 2023. Still now not reflected on Streamlit component library. How can I make our component to appears on the Streamlit component page.

## Details

**Name of the component**: EJ2-Streamlit-Grid
**Github URL**: https://github.com/SyncfusionExamples/Getting-started-with-Syncfusion-Grid-component-in-Streamlit-app
**PyPI package**: https://pypi.org/project/ej2-streamlit-grids/

**Comment by sfc-gh-dmatthews** [comment]
Hi @Vishnu-Moorthi,

Your component has been added to the gallery:
![image](https://github.com/streamlit/docs/assets/135349133/a8aa07a5-bb20-4e44-a6d2-02c95d76bf2d)

If you have any questions about the gallery or have more components in the future, please feel free to reach out to us on [our forums](https://discuss.streamlit.io/c/streamlit-components/18). We gather components from our community primarily from there.
