### ISSUE TITLE
Solution to "The app is attempting to load the component from ****, and hasn’t received its “streamlit ” message."

### ISSUE THREAD

**Issue by mkleinbort-ic** [streamlit/docs#760]
### Problem

A number of streamlit components work poorly when deployed to Azure Container Apps / Google's App Run

This has been reported a number of times as an issue:
- https://discuss.streamlit.io/t/the-app-is-attempting-to-load-the-component-from-and-hasnt-received-its-streamlit-message/36968
- https://github.com/PablocFonseca/streamlit-aggrid/issues/7
- https://github.com/okld/streamlit-ace/issues/13

This seems to be due to some delay in how the components load style sheets from remote URLs

### Solution

I propose that these style sheets be cached locally so that they can be included in a docker image - improving load times and user experience.

**Comment by carolinedlu** [comment]
Hi @mkleinbort-ic, I think this is a request for the Python library (not our docs), and it looks like you've created a [separate Issue in the main repo](https://github.com/streamlit/streamlit/issues/7046), so we should probably close this one for clarity
