### ISSUE TITLE
The link to the conda virtual environment showing 404(Screenshot attached)

### ISSUE THREAD

**Issue by zabihshaik** [streamlit/docs#810]
### Summary

I had tried to open the url for installing conda virtual environment as mentioned in the installation page. But, the url linked to it showing 404 Error(Screenshot attached).

### Steps to reproduce

Code snippet:

```

```

Screenshot(s):

(Please provide a code snippet and/or screenshots! These will help expedite us finding and solving the problem.)

![streamlit-docs-anaconda-error](https://github.com/streamlit/docs/assets/91183455/8e69eaf8-9c7d-4e89-8aad-26f3e84eda94)

If applicable, please provide the steps we should take to reproduce the bug:

1. Go to '[installation guide](https://docs.streamlit.io/library/get-started/installation)'
2. Scroll down to 'Set the virtual environment step' 
3. Click on 'conda' .

**Expected behavior:**

I would like to see the anaconda installation page.

**Actual behavior:**

Showing 404 Error.

### Is this a regression?

That is, did this use to work the way you expected in the past?
yes / no - Don't know as this was my first time installing Streamlit

### Debug info

- Docs page link: (do you have a link to the docs page containing the bug?) https://docs.streamlit.io/library/get-started/installation
- npm version: (get it with `npm -v`)
- node version: (get it with `node -v`)
- OS version: Windows 11
- Browser version:

### Additional information

If needed, add any other context about the problem here. For example, did this bug come from <https://discuss.streamlit.io> or another site? Link the original source here! [docs.s](https://docs.streamlit.io/)

**Comment by sfc-gh-dmatthews** [comment]
Thanks @zabihshaik for reporting the issue. I am putting in a correction right now.
