### ISSUE TITLE
toggle and data_editor missing from list of on_change widgets

### ISSUE THREAD

**Issue by sfc-gh-jcarroll** [streamlit/docs#841]
### Summary

In the list [here](https://docs.streamlit.io/library/api-reference/session-state#use-callbacks-to-update-session-state), st.toggle is missing even though it supports `on_change`

Might consider removing this list and just pointing to the "inputs widgets" section, since I think they are all supported?

**Comment by sfc-gh-jcarroll** [comment]
Oh, same for st.data_editor

**Comment by sfc-gh-dmatthews** [comment]
Thanks @sfc-gh-jcarroll. An edit is in a PR and should be merged by tomorrow.
