### ISSUE TITLE
Redrawable types should be documented

### ISSUE THREAD

**Issue by monchier** [streamlit/docs#88]
Related to this: https://discuss.streamlit.io/t/force-redraw-of-an-earlier-element/635

Please add documentation of which types in `DeltaGenerator` are redrawable.

**Comment by snehankekre** [comment]
Closing this issue as it has not come up since 2019.

**Comment by ivanmkc** [comment]
I have an issue where I need to update the earlier section:

```
        if self.view_model.mode == "A":
            with st.container():
                st.header("A")
                next_button_tapped = st.button("Go to b")

                if next_button_tapped:
                    self.view_model.mode = "B"

        elif self.view_model.mode == "B":
            with st.container():
                st.header("B")
                next_button_tapped = st.button("Go to A")

                if next_button_tapped:
                    self.view_model.mode = "A"
```

The problem is that the `mode` attribute is updated after the "redraw", so I have to it only works if I tap the button "twice". Once to set it, and once to redraw.
