### ISSUE TITLE
Example in documentation doesn't work

### ISSUE THREAD

**Issue by digitalghost-dev** [streamlit/docs#880]
### Checklist

- [X] I have searched the [existing issues](https://github.com/streamlit/streamlit/issues) for similar issues.
- [X] I added a very descriptive title to this issue.
- [X] I have provided sufficient information below to help reproduce this issue.

### Summary

I've started reading the docs on running tests and came across this [page](https://docs.streamlit.io/library/advanced-features/app-testing/get-started#example-project-with-app-testing) in the docs. In the example for `app.py`, it doesn't work and returns an error:
```
AttributeError: st.session_state has no attribute "beans". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization
```

### Reproducible Code Example

```Python
"""app.py"""
import streamlit as st

# Initialize st.session_state.beans
beans = st.session_state.get("beans", 0)

st.title("Bean counter :paw_prints:")

addend = st.number_input("Beans to add", 0, 10)
if st.button("Add"):
    st.session_state.beans += addend
st.markdown(f"Beans counted: {st.session_state.beans}")
```

### Steps To Reproduce

1. Paste the code in an editor and run with `streamlit run app,py`.

### Expected Behavior

As an example, it should run with no errors and allow the counter to work. `pytest` also fails.

### Current Behavior

Error:
```
AttributeError: st.session_state has no attribute "beans". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization
```

### Is this a regression?

- [ ] Yes, this used to work in a previous version.

### Debug info

- Streamlit version: 1.28.2
- Python version: 3.11.6
- Operating System: macOS
- Browser: Safari

### Additional Information

This modified code works and passes the test in the doc example:
```python
import streamlit as st

# Title
st.title("Bean counter :paw_prints:")

# Check if 'beans' is not in session_state, then initialize it
if 'beans' not in st.session_state:
    st.session_state.beans = 0

addend = st.number_input("Beans to add", 0, 10)

if st.button("Add"):
    st.session_state.beans += addend

st.markdown(f"Beans counted: {st.session_state.beans}")
```

**Comment by snehankekre** [comment]
@digitalghost-dev The issue has been fixed with #881. 😄 Please let us know if you spot other issues. 🎈
