### ISSUE TITLE
st.graphviz_chart examples not rendering

### ISSUE THREAD

**Issue by andfanilo** [streamlit/docs#90]
# Summary

Was working on providing a small example of using graphviz to render Decision Tree in streamlit/streamlit#1330 but code did not work. Then tried the 2 examples from API reference and none worked on my machine. Then tried [this one](https://github.com/streamlit/streamlit/issues/341#issuecomment-541150926). All got the same errors about viz not being defined :thinking: is it only me ?

# Steps to reproduce

```python
graph = graphviz.Digraph()
graph.edge('run', 'intr')
graph.edge('intr', 'runbl')
graph.edge('runbl', 'run')
graph.edge('run', 'kernel')
graph.edge('kernel', 'zombie')
graph.edge('kernel', 'sleep')
graph.edge('kernel', 'runmem')
graph.edge('sleep', 'swap')
graph.edge('swap', 'runswap')
graph.edge('runswap', 'new')
graph.edge('runswap', 'runmem')
graph.edge('new', 'runmem')
graph.edge('sleep', 'runmem')
st.graphviz_chart(graph)

st.graphviz_chart('''
    digraph {
        run -> intr
        intr -> runbl
        runbl -> run
        run -> kernel
        kernel -> zombie
        kernel -> sleep
        kernel -> runmem
        sleep -> swap
        swap -> runswap
        runswap -> new
        runswap -> runmem
        new -> runmem
        sleep -> runmem
    }
''')
```

## Expected behavior:

Displays graph

## Actual behavior:

Frontend logs for me 

```
Loading script from “http://localhost:8501/vendor/viz/viz-1.8.0.min.js” with importScripts() was blocked because of a disallowed MIME type (“text/plain”).
NetworkError: WorkerGlobalScope.importScripts: Failed to load worker script at http://localhost:8501/vendor/viz/viz-1.8.0.min.js
uncaught exception: Viz is not defined
```

## Is this a regression?

Probably

# Debug info

- Streamlit 0.57.4.dev20200408  and 0.57.3
- Python 3.7
- Conda, Windows 7 64 bit, Firefox

**Comment by snehankekre** [comment]
Closing this issue as one already exists in the Streamlit library repo: https://github.com/streamlit/streamlit/issues/3887
