### ISSUE TITLE
Incorrect variable is used in st.write in batch-elements-widgets.md

### ISSUE THREAD

**Issue by gireeshp** [streamlit/docs#907]
### Summary

In batch-elements-widgets.md, it shows the syntaxes for capturing the user input and submit functionalities. At the end trying to write the captured user input. However, an incorrect variable ("name") is used while writing when the captured user input is in the variable "text_input".

Code snippet:

```
with st.form(key='my_form'):
    text_input = st.text_input(label='Enter your name')
    submit_button = st.form_submit_button(label='Submit')

if submit_button:
    st.write(f'hello {name}')
```

Screenshot(s):
![image](https://github.com/streamlit/docs/assets/4717349/92a78783-0581-45c6-b17f-4b5d9238552e)

**Comment by sfc-gh-dmatthews** [comment]
Closing this issue since the correction is merged. Thanks @gireeshp!
