### ISSUE TITLE
Table rendering in markdown appears to be broken

### ISSUE THREAD

**Issue by Asaurus1** [streamlit/docs#918]
### Summary

From https://docs.streamlit.io/library/advanced-features/caching
![image](https://github.com/streamlit/docs/assets/5677417/99e711f8-196b-4174-b920-0e08030069b0)
Markdown tables are not rendering properly in HTML. This screenshot is from the official (compiled) docs but I am also able to reproduce the issue when running npm in dev mode locally.

AutoFunction tables for the API reference still render correctly (probably because they're pure React/HTML).

### Steps to reproduce

Appears to happen on any *.md page in the docs (tried on caching.md and cli.md on the current main branch [621d901b7]).

Screenshot(s):
![image](https://github.com/streamlit/docs/assets/5677417/99e711f8-196b-4174-b920-0e08030069b0)

Corresponding markdown:
```
When benchmarking `st.cache_data` on pandas DataFrames with four columns, we found that it becomes slow when going beyond 100 million rows. The table shows runtimes for both caching decorators at different numbers of rows (all with four columns):


|                   |                 | 10M rows | 50M rows | 100M rows | 200M rows |
| ----------------- | --------------- | :------: | :------: | :-------: | :-------: |
| st.cache_data     | First run\*     |  0.4 s   |   3 s    |   14 s    |   28 s    |
|                   | Subsequent runs |  0.2 s   |   1 s    |    2 s    |    7 s    |
| st.cache_resource | First run\*     |  0.01 s  |  0.1 s   |   0.2 s   |    1 s    |
|                   | Subsequent runs |   0 s    |   0 s    |    0 s    |    0 s    |

|                                                                                                                                                              |
| :----------------------------------------------------------------------------------------------------------------------------------------------------------- |
| _\*For the first run, the table only shows the overhead time of using the caching decorator. It does not include the runtime of the cached function itself._ |
```

**Expected behavior:**

Tables should render properly in HTML. 

**Actual behavior:**

Markdown tables as plaintext

### Is this a regression?

Unclear if this is a regression or a feature that never worked in the first place

### Debug info

- Docs page link: (do you have a link to the docs page containing the bug?) See above
- npm version: (get it with `npm -v`) 9.8.1
- node version: (get it with `node -v`) v20.6.1
- OS version: Windows 11, but it's also on the compiled files on the official site docs.
- Browser version: Chrome, Opera

### Additional information

Tried to trace back how markdown rendering happens, it appears we use [frontmatter-markdown-loader](https://www.npmjs.com/package/frontmatter-markdown-loader), which in turn uses https://github.com/markdown-it/markdown-it by default to render the markdown to HTML. markdown-it claims to support GFM Tables by default, but perhaps that plugin is getting disabled somewhere.

**Comment by Asaurus1** [comment]
@sfc-gh-jcarroll I noticed this the other day while looking on the official docs for something ... not sure how recent of a regression this is (if it's a regression at all), but I couldn't find an open ticket for anything like it so I made this one.

**Comment by sfc-gh-jcarroll** [comment]
Nice find, thanks! cc @sfc-gh-dmatthews

**Comment by sfc-gh-dmatthews** [comment]
We updated some dependencies around Christmas, so my best guess is it's related to that, but I'll take a look. Thanks!
