### ISSUE TITLE
Files not tracked if folder doesn't have __init__.py

### ISSUE THREAD

**Issue by kmcentush** [streamlit/docs#92]
# Summary

I recently came across this issue and couldn't find anything in the documentation that called it out. I figured that either this is truly a bug, or the documentation should be updated to include a comment on this so that other users aren't caught off guard like I was.

# Steps to reproduce

1. Create the following file structure. Fill each file as shown
```
app/
├── pages/
│    ├──page1.py
└── main.py
```

main.py:
```
import streamlit as st

from pages import page1

st.write('Main')
page1.display()
```

page1.py:
```
import streamlit as st

def display():
    st.write('Page 1')
```

2. Run `streamlit run main.py`
3. Change the text that's displaying in main.py. The streamlit app will offer to rerun in the browser as normal.
4. Change the text that's displaying in page1.py. The streamlit app will _not_ offer to rerun. Any code changes to this file will not appear unless you restart the streamlit app from the command line.

## Expected behavior:

Changing code in any files in subfolders would also be detected by Streamlit.

## Actual behavior:

The changes in the subfolder files aren't detected by Streamlit.

## Workaround:
Simply adding an empty `__init__.py` to `pages/`, killing the app, then restarting it will fix the issue. The working folder structure then looks like this:
```
app/
├── pages/
│   ├── __init__.py
│   └── page1.py
└── main.py
```

## Is this a regression?

No idea, but probably not.

# Debug info

- Streamlit version: 0.62.1
- Python version: 3.7.4

**Comment by snehankekre** [comment]
This issue was fixed by #18. There is a [KB article](https://docs.streamlit.io/knowledge-base/using-streamlit/streamlit-watch-changes-other-modules-importing-app) documenting the behavior.
