### ISSUE TITLE
E: Unable to locate package python-openssl

### ISSUE THREAD

**Issue by crimson206** [streamlit/docs#973]
**Link to doc page in question (if any):**
https://github.com/streamlit/streamlit/wiki/Contributing

**Name of the Streamlit feature whose docs need improvement:**
When I try to run the line below, it causes the error in the title.
It was solved as I replaced python-openssl by python3-openssl in my case.

--- below ---
sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev python-openssl mysql-client libmysqlclient-dev unixodbc-dev

**What you think the docs should say:**
I don't know. I just wanted to let you know.

**Comment by sfc-gh-dmatthews** [comment]
This has been corrected. Thanks!
