### ISSUE TITLE
Provide warning that dates are silently adjusted for the user's timezone

### ISSUE THREAD

**Issue by SimonBiggs** [streamlit/docs#98]
**Link to doc page in question (if any):**
https://docs.streamlit.io/en/stable/api.html#streamlit.line_chart

**Name of the Streamlit feature whose docs need improvement:**
`st.line_chart`

**What you think the docs should say:**
```rst
.. warning::
    Date formatted data will be adjusted for the user's timezone before being plotted on the ``st.line_chart``.
```

**Details of issue:**
The following image:

![image](https://user-images.githubusercontent.com/6559099/100163980-ffa34280-2f0a-11eb-9dc2-1ac6ae12f63b.png)

is produced by the following code:

```python
st.write(icom_datasets)
st.line_chart(icom_datasets[["gantry", "collimator", "turn_table"]])
```

The plot and the dataframe print is produced by the same dataframe. The plot however silently removes (?) a presumed GMT+11 shift.

**Comment by snehankekre** [comment]
In the above case, I suspect Altair is the one doing the conversion: https://altair-viz.github.io/user_guide/times_and_dates.html?highlight=time 

We've added a section on working with timezones in Streamlit: https://docs.streamlit.io/library/advanced-features/timezone-handling
